package auth

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/abigotado/youtrack-agent-cli/internal/profile"
)

const compensationTimeout = 3 * time.Second

// ProfileRegistry is the metadata boundary used by login and logout.
type ProfileRegistry interface {
	WithProfileLock(ctx context.Context, name string, fn func() error) error
	Get(ctx context.Context, name string) (profile.Profile, error)
	Add(ctx context.Context, p profile.Profile) error
	Put(ctx context.Context, p profile.Profile) error
	Remove(ctx context.Context, name string) error
}

// Login saves the credential before publishing its profile metadata.
// Replacing an existing credential requires overwriteConfirmed; attaching the
// first credential to the required metadata-only profile does not.
func Login(
	ctx context.Context,
	store CredentialAccessStore,
	registry ProfileRegistry,
	p profile.Profile,
	credential Credential,
	overwriteConfirmed bool,
) (profile.Profile, error) {
	if store == nil || registry == nil {
		return profile.Profile{}, errors.New("login dependencies are required")
	}
	if err := p.ValidateLoginIntent(); err != nil {
		return profile.Profile{}, err
	}
	if err := credential.Validate(); err != nil {
		return profile.Profile{}, err
	}
	if credential.ProfileIdentity != "" || credential.Generation != "" || len(credential.Capabilities) != 0 {
		return profile.Profile{}, errors.New("credential binding is generated by login")
	}

	var stored profile.Profile
	err := registry.WithProfileLock(ctx, p.Name, func() error {
		var err error
		stored, err = loginLocked(ctx, store, registry, p, credential, overwriteConfirmed)
		return err
	})
	if err != nil {
		return profile.Profile{}, err
	}
	return stored, nil
}

func loginLocked(ctx context.Context, store CredentialAccessStore, registry ProfileRegistry, p profile.Profile, credential Credential, overwriteConfirmed bool) (profile.Profile, error) {
	previousProfile, registryLookupErr := registry.Get(ctx, p.Name)
	profileExists := registryLookupErr == nil
	if errors.Is(registryLookupErr, profile.ErrNotFound) {
		return profile.Profile{}, fmt.Errorf("%w: %s", ErrProfileChangedDuringLogin, p.Name)
	}
	if registryLookupErr != nil && !errors.Is(registryLookupErr, profile.ErrNotFound) {
		return profile.Profile{}, fmt.Errorf("check existing profile: %w", registryLookupErr)
	}
	if profileExists {
		currentIntent, err := previousProfile.LoginIntent()
		if err != nil {
			return profile.Profile{}, fmt.Errorf("validate current profile during login: %w", err)
		}
		if !profilesEqual(currentIntent, p) {
			return profile.Profile{}, fmt.Errorf("%w: %s", ErrProfileChangedDuringLogin, p.Name)
		}
	}
	credentialExists, credentialLookupErr := store.Exists(ctx, p.Name)
	if credentialLookupErr != nil {
		return profile.Profile{}, fmt.Errorf("check existing credential: %w", credentialLookupErr)
	}
	if credentialExists && !overwriteConfirmed {
		return profile.Profile{}, fmt.Errorf("%w: %s", ErrOverwriteConfirmationRequired, p.Name)
	}
	var previousCredential Credential
	if credentialExists {
		previousCredential, credentialLookupErr = store.Load(ctx, p.Name)
		if credentialLookupErr != nil {
			return profile.Profile{}, fmt.Errorf("load existing credential: %w", credentialLookupErr)
		}
	}
	modernProfile, err := p.WithNewCredentialGeneration()
	if err != nil {
		return profile.Profile{}, err
	}
	p = modernProfile
	credential, err = BindCredential(credential, p)
	if err != nil {
		return profile.Profile{}, err
	}
	if err := store.Save(ctx, p.Name, credential); err != nil {
		return profile.Profile{}, fmt.Errorf("save credential: %w", err)
	}

	var registryErr error
	if profileExists && profilesEqual(previousProfile, p) {
		return p, nil
	}
	if profileExists {
		registryErr = registry.Put(ctx, p)
	} else {
		registryErr = registry.Add(ctx, p)
	}
	if registryErr == nil {
		return p, nil
	}
	if profile.WasCommitted(registryErr) {
		return profile.Profile{}, fmt.Errorf("profile metadata committed with a durability warning: %w", registryErr)
	}
	compensationContext, cancel := context.WithTimeout(context.WithoutCancel(ctx), compensationTimeout)
	defer cancel()
	rollbackErr := rollbackCredential(compensationContext, store, p.Name, previousCredential, credentialExists)
	if rollbackErr != nil {
		return profile.Profile{}, errors.Join(fmt.Errorf("save profile metadata: %w", registryErr), fmt.Errorf("rollback credential: %w", rollbackErr))
	}
	return profile.Profile{}, fmt.Errorf("save profile metadata: %w", registryErr)
}

// MigrateKeychain changes only the access policy of the exact credential for
// an existing profile. It never loads the credential value or contacts
// YouTrack.
func MigrateKeychain(ctx context.Context, store CredentialAccessStore, registry ProfileRegistry, profileName string) error {
	if store == nil || registry == nil {
		return errors.New("keychain migration dependencies are required")
	}
	if err := profile.RequireName(profileName); err != nil {
		return err
	}
	return registry.WithProfileLock(ctx, profileName, func() error {
		if _, err := registry.Get(ctx, profileName); err != nil {
			return fmt.Errorf("load profile for keychain migration: %w", err)
		}
		exists, err := store.Exists(ctx, profileName)
		if err != nil {
			return translateMigrationStoreError(err)
		}
		if !exists {
			return ErrKeychainEntryNotFound
		}
		if err := store.MigrateKeychain(ctx, profileName); err != nil {
			return translateMigrationStoreError(err)
		}
		return nil
	})
}

func translateMigrationStoreError(err error) error {
	switch {
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return err
	case errors.Is(err, ErrNotFound):
		return fmt.Errorf("%w: %v", ErrKeychainEntryNotFound, err)
	case errors.Is(err, ErrInteractionNotAllowed):
		return fmt.Errorf("%w: %v", ErrKeychainMigrationBlocked, err)
	case errors.Is(err, ErrKeychainMigrationCanceled):
		return err
	case errors.Is(err, ErrUnsupported):
		return fmt.Errorf("%w: %v", ErrKeychainMigrationUnavailable, err)
	default:
		return err
	}
}

func profilesEqual(left, right profile.Profile) bool {
	return profile.CredentialIdentity(left) == profile.CredentialIdentity(right)
}

// Logout deletes the credential before removing its public metadata.
func Logout(ctx context.Context, store CredentialStore, registry ProfileRegistry, profileName string) error {
	if store == nil || registry == nil {
		return errors.New("logout dependencies are required")
	}
	if err := profile.RequireName(profileName); err != nil {
		return err
	}
	return registry.WithProfileLock(ctx, profileName, func() error {
		previous, loadErr := store.Load(ctx, profileName)
		credentialExisted := loadErr == nil
		if loadErr != nil && !errors.Is(loadErr, ErrNotFound) {
			return fmt.Errorf("load credential for logout: %w", loadErr)
		}
		if err := store.Delete(ctx, profileName); err != nil {
			return fmt.Errorf("delete credential: %w", err)
		}
		registryErr := registry.Remove(ctx, profileName)
		if registryErr == nil {
			return nil
		}
		if errors.Is(registryErr, profile.ErrNotFound) {
			return nil
		}
		if profile.WasCommitted(registryErr) {
			return fmt.Errorf("profile metadata removal committed with a durability warning: %w", registryErr)
		}
		compensationContext, cancel := context.WithTimeout(context.WithoutCancel(ctx), compensationTimeout)
		defer cancel()
		if credentialExisted {
			if restoreErr := store.Save(compensationContext, profileName, previous); restoreErr != nil {
				return errors.Join(
					fmt.Errorf("remove profile metadata: %w", registryErr),
					fmt.Errorf("restore credential after failed logout: %w", restoreErr),
				)
			}
		}
		return fmt.Errorf("remove profile metadata: %w", registryErr)
	})
}

func rollbackCredential(ctx context.Context, store CredentialStore, profileName string, previous Credential, restore bool) error {
	if restore {
		return store.Save(ctx, profileName, previous)
	}
	return store.Delete(ctx, profileName)
}
